"use client";
import { useMemo, useState } from "react";

const events = [
  {title:"North Coast Sessions",category:"Music",date:"12 Sep",month:"September",city:"Ayr",price:32,status:"Selling fast",image:"https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1000&q=85",slug:"north-coast-sessions"},
  {title:"Field & Flame Festival",category:"Food & drink",date:"20 Sep",month:"September",city:"Glasgow",price:18,status:"Good availability",image:"https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1000&q=85",slug:"field-and-flame-festival"},
  {title:"A Midsummer Night’s Dream",category:"Theatre",date:"24 Sep",month:"September",city:"Edinburgh",price:24,status:"Last few",image:"https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1000&q=85",slug:"a-midsummer-nights-dream"},
  {title:"Little Explorers Live",category:"Family",date:"3 Oct",month:"October",city:"Dundee",price:12,status:"Good availability",image:"https://images.unsplash.com/photo-1472653431158-6364773b2a56?auto=format&fit=crop&w=1000&q=85",slug:"little-explorers-live"},
  {title:"City 10K & Festival",category:"Sport",date:"11 Oct",month:"October",city:"Stirling",price:20,status:"Entries open",image:"https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=1000&q=85",slug:"city-10k-and-festival"},
  {title:"Afterlight Orchestra",category:"Music",date:"23 Oct",month:"October",city:"Aberdeen",price:28,status:"Just announced",image:"https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1000&q=85",slug:"afterlight-orchestra"},
];
const categories=["All","Music","Food & drink","Theatre","Family","Sport"];

export default function EventsPage(){
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("All"); const [city,setCity]=useState("All locations"); const [month,setMonth]=useState("Any date"); const [sort,setSort]=useState("Recommended"); const [saved,setSaved]=useState<string[]>([]);
 const filtered=useMemo(()=>events.filter(e=>(category==="All"||e.category===category)&&(city==="All locations"||e.city===city)&&(month==="Any date"||e.month===month)&&(`${e.title} ${e.city}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>sort==="Price: low to high"?a.price-b.price:0),[query,category,city,month,sort]);
 return <main className="inner-page" id="top"><section className="page-hero events-hero"><p className="eyebrow">Make plans worth keeping</p><h1>Find your<br/>next event.</h1><p>From one-night-only performances to weekends you’ll never forget.</p><label className="directory-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by event, artist or city" aria-label="Search events"/><button onClick={()=>document.getElementById("results")?.scrollIntoView({behavior:"smooth"})}>Search</button></label></section><section className="directory" id="results"><div className="discovery-controls"><div className="category-chips">{categories.map(item=><button className={category===item?"active":""} onClick={()=>setCategory(item)} key={item}>{item}</button>)}</div><div className="select-filters"><select value={month} onChange={e=>setMonth(e.target.value)} aria-label="Date"><option>Any date</option><option>September</option><option>October</option></select><select value={city} onChange={e=>setCity(e.target.value)} aria-label="Location"><option>All locations</option>{[...new Set(events.map(e=>e.city))].map(c=><option key={c}>{c}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort events"><option>Recommended</option><option>Price: low to high</option></select></div></div><div className="filter-bar"><strong>{filtered.length} events</strong><a href="/saved">View saved events ♡</a></div><div className="directory-grid">{filtered.map(e=><article key={e.title}><div className="directory-image"><a href={`/events/${e.slug}`}><img src={e.image} alt=""/><span className={`availability ${e.status==="Last few"||e.status==="Selling fast"?"urgent":""}`}>{e.status}</span></a><button className={saved.includes(e.slug)?"saved":""} onClick={()=>setSaved(s=>s.includes(e.slug)?s.filter(x=>x!==e.slug):[...s,e.slug])} aria-label={`Save ${e.title}`}>{saved.includes(e.slug)?"♥":"♡"}</button></div><div><p>{e.category} · {e.date}</p><h2><a href={`/events/${e.slug}`}>{e.title}</a></h2><span>{e.city}</span><strong>From £{e.price}</strong><a className="directory-ticket" href={`/events/${e.slug}`}>View event & tickets ↗</a></div></article>)}</div>{!filtered.length&&<div className="empty-state"><h3>No events match those filters</h3><p>Try a different category, date or location.</p></div>}</section></main>
}
